modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/ToCraft/woodwalkers-mod/issues"
displayURL = "https://github.com/ToCraft/woodwalkers-mod"
license = "MIT"

[[mixins]]
config = "walkers-neoforge.mixins.json"
[[mixins]]
config = "walkers.mixins.json"

[[mods]]
modId = "walkers"
version = "${version}"
displayName = "Walkers"
authors = "To_Craft"
credits = "Original mod by Draylar"
description = '''
Become a Woodwalker/animagus!
'''
logoFile = "pack.png"

[[dependencies.walkers]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walkers]]
modId = "craftedcore"
mandatory = true
type = "required"
versionRange = "[${craftedcore_version},)"
ordering = "AFTER"
side = "BOTH"
