name: Build

on:
  push:
    paths:
      - '**.gradle'
      - '**.gradle.kts'
      - '**.properties'
      - '**/src/**'
    branches-ignore:
      - "1.**"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew check build --parallel

      - name: Setting mod version
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^archives_base_name= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version= >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: "${{ env.archives_base_name }}-${{ env.mod_version }}"
          path: |
            build/**/**/libs/
            !build/*/libs/
            !build/libs/
            !**/*-dev.jar
            !**/*-shadow.jar
            !**/*-transformProduction*.jar
            !**/testmod*/