name: Build and Release

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
    branches:
      - "1.**"
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: false
        default: 'true'
      discord_message:
        description: 'Discord Message'
        required: false
        default: 'false'

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build files
        run: ./gradlew check build --parallel

      - name: Setting mod version
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^archives_base_name= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^minecraft_version= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version= >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: "[${{ env.minecraft_version }}] ${{ env.archives_base_name }}-${{ env.mod_version }}"
          path: |
            **/build/libs/
            !build/libs/
            !**/*-dev.jar
            !**/*-shadow.jar
            !**/*-transformProduction*.jar
            !**/testmod*/
  release:
    name: "Release"
    needs: build
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[no_release]') && github.event.inputs.release != 'false'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Extract Artifact Type
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^artifact_type= >> $GITHUB_ENV

      - name: Publish to Maven, CurseForge & Modrinth
        run: ./gradlew publish modrinth curseforge --parallel
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Extract Changelog for GitHub
        run: ./gradlew extractNewestChangelog --parallel
      - name: Create version data
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^archives_base_name= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^minecraft_version= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version= >> $GITHUB_ENV
      - name: Create version name
        run: echo "version_name_git=$minecraft_version-$mod_version" >> $GITHUB_ENV
      - name: Create GitHub Tag
        if: |
          ${{ env.artifact_type }} == 'release'
        uses: EndBug/latest-tag@latest
        with:
          ref: "${{ env.version_name_git }}"
      - name: Create GitHub Release
        if: |
          ${{ env.artifact_type }} == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.version_name_git }}"
          files: |
            fabric/build/libs/${{ env.archives_base_name }}-${{ env.mod_version }}-fabric.jar,
            forge/build/libs/${{ env.archives_base_name }}-${{ env.mod_version }}-forge.jar,
            neoforge/build/libs/${{ env.archives_base_name }}-${{ env.mod_version }}-neoforge.jar
          body_path: ${{ github.workspace }}/extracted.CHANGELOG.md
  discord_message:
    name: "Send Discord Release Message"
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.discord_message == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Send Discord Message
        run: ./gradlew discordRelease --parallel
        env:
          DISCORD_WEB_HOOK: ${{ secrets.DISCORD_WEB_HOOK }}